### ISSUE TITLE
Finish support for workflow

### ISSUE THREAD

**Issue by mark-burnett** [genome/ptero-perl-sdk#25]
Including the ability to query workflow status, wait for the workflow and cancel it.

**Comment by mark-burnett** [comment]
Some of this was done in #34, but canceling and querying detailed workflow status are not yet supported by the service, so this is currently blocked.

**Comment by davidlmorton** [comment]
Workflow status is the only thing not supported at this time.  Canceling is off the table for the 'initial deployment' phase.

**Comment by mkiwala** [comment]
Submission and waiting for a workflow to complete are implemented. Testing of these features are in #35.

Closing this in lieu of independent tickets for canceling workflows and query detailed workflow status.
