### ISSUE TITLE
Support top-level parallel-by

### ISSUE THREAD

**Issue by mkiwala** [genome/ptero-perl-sdk#37]

**Comment by davidlmorton** [comment]
This was fixed by not allowing top-level parallel-by.  The Genome integration will take care to enclose any top-level parallel-by with a non-parallel-by workflow.  So top-level parallel by is supported in workflow.xml but not in our json representation.

**Comment by davidlmorton** [comment]
This was fixed by not supporting top-level parallel-by in the json representation.  It is still supported in the workflow.xml representation, but is automatically nested inside of a non-parallel-by workflow by the Genome adaptor layer.
